FROM --platform=linux/amd64 mcs07/postgres-rdkit:latest


HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=5 \
    CMD pg_isready -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-flaskai}" \
    || exit 1
